language: node_js
node_js:
  - '12'
os:
  - linux
addons:
  apt:
    packages:
      - zip
before_deploy:
  - sh ./build-binary.sh
deploy:
  provider: releases
  api_key:
    secure: adeL+UGFBd5kDqN+7zN8j55ngskdM+KtSt58UWNajscKpc8D9Sqj7cPKECpIbhbAqaERZV6fcfrRlFSHW5BGfeZjPuU++SlWrmVewycaehnVbBnXoMHtBfTL9KUc5uOHlMSxwyd+FtS5N00DrNsR2coPA8b3Zi4DOYM8PVpQ6LU=
  file_glob: true
  file:
    ../enketo-validate-binaries/*.zip
  skip_cleanup: true
  on:
    tags: true
    repo: enketo/enketo-validate
    branch: master
